name: 'choose Ubuntu mirror for PowerDNS builds in Github Actions'
runs:
  using: "composite"
  steps:
    #- run: echo not changing mirror, using default Azure mirror
    #  shell: bash
    - run: sudo sed -i 's/azure\.archive\.ubuntu\.com/mirror.leaseweb.net/' /etc/apt/sources.list
      shell: bash
    - run: "echo -e 'Package: *\nPin: origin \"mirror.leaseweb.net\"\nPin-Priority: 1001' | sudo tee /etc/apt/preferences"
      shell: bash
