---
name: 'Test IPv6'

on:
  push:

permissions: # least privileges, see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
  contents: read

env:
  CLANG_VERSION: '13'
  # github.workspace variable points to the Runner home folder. Container home folder defined below.
  REPO_HOME: '/__w/pdns/pdns'

jobs:
  test:
    name: test container ipv6
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/powerdns/base-pdns-ci-image/debian-11-pdns-base:master
      env:
        ASAN_OPTIONS: detect_leaks=0
        FUZZING_TARGETS: yes
        SANITIZERS: asan+ubsan
        UBSAN_OPTIONS: "print_stacktrace=1:halt_on_error=1:suppressions=${{ env.REPO_HOME }}/build-scripts/UBSan.supp"
        UNIT_TESTS: yes
        PDNS_TEST_NO_IPV6: yes
      options: --sysctl net.ipv6.conf.all.disable_ipv6=0
    steps:
      - run: ip a
      - run: ifconfig -a
