---
name: Build docker images

on:
  workflow_call:
    inputs:
      product:
        required: true
        description: Product to build
        type: string
      ref:
        description: git ref to checkout
        type: string
        default: master
        required: false
      image-name:
        description: repository name for the requested image
        type: string
        required: true
      image-tags:
        description: tag for the requested image
        type: string
        required: true
      image-description:
        description: short description for the image repository
        type: string
        required: true
      platforms:
        description: target platform(s) for the image to be built
        type: string
        default: linux/arm64/v8,linux/amd64
        required: false
      push:
        description: push image to DockerHub
        type: boolean
        required: true
    secrets:
      DOCKERHUB_ORGANIZATION_NAME:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

permissions: # least privileges, see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
  contents: read

env:
  DOCKERHUB_ORGANIZATION_NAME: romeroalx

jobs:
  build:
    name: build docker image for a product
    runs-on: ubuntu-22.04
    outputs:
      image-digest: ${{ steps.build-image.outputs.digest }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          ref: ${{ inputs.ref }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64/v8
      - name: Set up Docker Buildx for multi-platform builds
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ inputs.platforms }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_ORGANIZATION_NAME }}/${{ inputs.image-name }}
          tags: ${{ inputs.image-tags }}
      - name: Build and load powerdns product images
        id: build-image
        run: |
          echo "digest=sha256:c0e14dc7de6ec291a711266cd04580b00b64d9a2b0277fe5fd1868147fe89a8c" >> $GITHUB_OUTPUT
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: Dockerfile-${{ inputs.product }}
      #     platforms: ${{ inputs.platforms }}
      #     push: ${{ inputs.push }}
      #     sbom: true
      #     tags: ${{ steps.meta.outputs.tags }}
      # - name: Update repo description
      #   if: ${{ inputs.push }}
      #   uses: peter-evans/dockerhub-description@v4
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #     repository: ${{ secrets.DOCKERHUB_ORGANIZATION_NAME }}/${{ inputs.image-name }}
      #     short-description: ${{ inputs.image-description }}

  test-image-amd64:    
    name: test uploaded amd64 images
    if: ${{ contains(inputs.platforms, 'amd64') && inputs.push }}
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Check running image
        run: |
          image_name='${{ secrets.DOCKERHUB_ORGANIZATION_NAME }}/${{ inputs.image-name }}'
          for i in `echo '${{ inputs.image-tags }}' | tr '\n' ' '`; do
            echo 'Testing: '${image_name}':'${i};
            docker run ${image_name}:${i} --version || [ "$?" == "134" ]
          done
      - name: Check image digest matches
        run: |
          output_digest='${{ needs.build.outputs.image-digest }}'
          image_name='${{ secrets.DOCKERHUB_ORGANIZATION_NAME }}/${{ inputs.image-name }}'
          echo 'output_digest: '${output_digest}
          echo 'image_name: '${image_name}
          for i in `echo '${{ inputs.image-tags }}' | tr '\n' ' '`; do
            image_digest=$(docker inspect --format='{{index .RepoDigests 0}}' ${image_name}:${i})
            [[ "${image_name}@{output_digest}" == "${image_digest}" ]] || echo "Image digest does not match" && exit 1
            echo
          done

  test-image-arm64:    
    name: test uploaded arm64 images
    if: ${{ contains(inputs.platforms, 'arm64') && inputs.push }}
    needs: build
    runs-on: ubicloud-standard-2-arm
    steps:
      - run: |
          for i in `echo '${{ inputs.image-tags }}' | tr '\n' ' '`; do
            echo 'Testing: ${{ secrets.DOCKERHUB_ORGANIZATION_NAME }}/${{ inputs.image-name }}:'$i;
            docker run '${{ secrets.DOCKERHUB_ORGANIZATION_NAME }}/${{ inputs.image-name }}:'$i --version || [ "$?" == "134" ]
          done
