---
name: Trigger workflow build-and-test-all for different releases

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 22 * * 4'

permissions: # least privileges, see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
  actions: read
  contents: read

jobs:
  call-build-and-test-all-master-debian-11:
    uses: romeroalx/pdns/.github/workflows/build-and-test-all.yml@test-py13
    with:
      branch-name: test-py13
      runner-docker-image-name: base-pdns-ci-image/debian-11-pdns-base-py13

  call-build-and-test-all-master-debian-12:
    uses: romeroalx/pdns/.github/workflows/build-and-test-all.yml@test-py13
    with:
      branch-name: test-py13
      runner-docker-image-name: base-pdns-ci-image/debian-12-pdns-base-py13

