---
name: Trigger specific image build

on:
  # push:
  workflow_dispatch:
    inputs:
      product:
        description: Product to build
        type: choice
        options:
        - authoritative
        - recursor
        - dnsdist

permissions: # least privileges, see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
  contents: read

jobs:
  call-coverity-auth:
    uses: romeroalx/pdns/.github/workflows/coverity.yml@test-fix-coverity
    with:
      product: authoritative
    secrets:
      COVERITY_TOKEN: ${{ secrets.COVERITY_TOKEN }}
      COVERITY_EMAIL: ${{ secrets.COVERITY_EMAIL }}

#   call-coverity-rec:
#     uses: romeroalx/pdns/.github/workflows/coverity.yml@test-fix-coverity
#     with:
#       product: recursor
#     secrets:
#       COVERITY_TOKEN: ${{ secrets.COVERITY_TOKEN }}
#       COVERITY_EMAIL: ${{ secrets.COVERITY_EMAIL }}
# 
#   call-coverity-dnsdist:
#     uses: romeroalx/pdns/.github/workflows/coverity.yml@test-fix-coverity
#     with:
#       product: dnsdist
#     secrets:
#       COVERITY_TOKEN: ${{ secrets.COVERITY_TOKEN }}
#       COVERITY_EMAIL: ${{ secrets.COVERITY_EMAIL }}
