---
  name: 'Test arm64 package building for specific distributions'
  
  on:
    push:
  
  permissions: # least privileges, see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
    contents: read
  
  jobs:
    build:
      name: build.sh
      runs-on: macos-14
      strategy:
        matrix:
          product: ['authoritative', 'recursor', 'dnsdist']
          os:
            - centos-7
            - el-8
            - centos-8-stream
            - centos-9-stream
            - ubuntu-lunar
            - ubuntu-mantic
            - ubuntu-noble
            - debian-bookworm
            - debian-trixie
            - amazon-2023
        fail-fast: false
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0  # for correct version numbers
            submodules: recursive
        # this builds packages and runs our unit test (make check)
        - run: builder/build.sh -v -m ${{ matrix.product }} ${{ matrix.os }}
        - name: Get version number
          run: |
            echo "version=$(readlink builder/tmp/latest)" >> $GITHUB_OUTPUT
          id: getversion
        - run: for i in `docker image ls | grep -v REPOSITORY | awk '{print $1":"$2}'`; do echo -n $i;  docker image inspect $i | grep Arch; echo; done
        - name: Upload packages
          uses: actions/upload-artifact@v4
          with:
            name: ${{ matrix.product }}-${{ matrix.os }}-${{ steps.getversion.outputs.version }}
            path: built_pkgs/
            retention-days: 7
  