---
name: 'daily: build packages for master'

on:
  push:
  schedule:
    - cron: '0 5 * * *'

permissions:
  actions: read
  id-token: write
  contents: write

jobs:
  call-build-packages-dnsdist:
    uses: romeroalx/pdns/.github/workflows/build-packages.yml@alma10
    with:
      is_release: 'NO'
      product: 'dnsdist'
      ref: ddist20-backport-15639
    secrets:
      DOWNLOADS_AUTOBUILT_SECRET: ${{ secrets.DOWNLOADS_AUTOBUILT_SECRET }}
      DOWNLOADS_AUTOBUILT_RSYNCTARGET: ${{ secrets.DOWNLOADS_AUTOBUILT_RSYNCTARGET }}
      DOWNLOADS_AUTOBUILT_HOSTKEY: ${{ secrets.DOWNLOADS_AUTOBUILT_HOSTKEY }}
