---
name: 'Test package building for specific distributions'

on:
  push:
  workflow_call:
    inputs:
      branch-name:
        description: 'Checkout to a specific branch'
        required: true
        default: ''
        type: string
  schedule:
    - cron: '0 1 * * *'

permissions: # least privileges, see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
  contents: read

jobs:
  build:
    name: build.sh
    # if: ${{ vars.SCHEDULED_JOBS_BUILDER }}
    # on a ubuntu-20.04 VM
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        product: ['authoritative', 'recursor', 'dnsdist']
        os:
          # - centos-7
          # - el-8
          # - centos-8-stream
          # - centos-9-stream
          # - ubuntu-lunar
          - ubuntu-mantic
          - ubuntu-noble
          # - debian-bookworm
          - debian-trixie
          # - amazon-2023
        platform: ['linux/amd64', 'linux/arm64/v8']
        exclude:
          - os: centos-7
            platform: linux/arm64/v8
          - os: el-8
            platform: linux/arm64/v8
          - os: centos-8-stream
            platform: linux/arm64/v8
          - os: centos-9-stream
            platform: linux/arm64/v8
          - os: amazon-2023
            platform: linux/arm64/v8
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # for correct version numbers
          submodules: recursive
          ref: ${{ inputs.branch-name }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: ${{ matrix.platform == 'linux/arm64/v8' }}
        with:
          platforms: ${{ matrix.platform }}
      - name: Set up Docker Buildx for multi-platform builds
        uses: docker/setup-buildx-action@v3
        if: ${{ matrix.platform == 'linux/arm64/v8' }}
        with:
          platforms: ${{ matrix.platform }}
      # this builds packages and runs our unit test (make check)
      - run: builder/build.sh -v -T ${{ matrix.platform }} -m ${{ matrix.product }} ${{ matrix.os }}
      - name: Get version number
        run: |
          echo "version=$(readlink builder/tmp/latest)" >> $GITHUB_OUTPUT
        id: getversion
      - name: Get target architecture
        run: |
          echo "target-arch=$(echo '${{ matrix.platform }}' | cut -d '/' -f 2)" >> $GITHUB_OUTPUT
        id: getarch
      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.product }}-${{ matrix.os }}-${{ steps.getarch.outputs.target-arch }}-${{ steps.getversion.outputs.version }}
          path: built_pkgs/
          retention-days: 7
