---
name: 'daily: build packages for master '

on:
  push:
  schedule:
    - cron: '0 5 * * *'

permissions:
  actions: read
  id-token: write
  contents: write

jobs:
  call-build-packages-auth:
    # if: ${{ vars.SCHEDULED_PACKAGES_DAILY }}
    uses: romeroalx/pdns/.github/workflows/build-packages.yml@test-pulp-file-repository
    with:
      is_release: 'NO'
      product: 'authoritative'
      ref: 'master'
    secrets:
      DOWNLOADS_AUTOBUILT_SECRET: ${{ secrets.DOWNLOADS_AUTOBUILT_SECRET }}
      DOWNLOADS_AUTOBUILT_RSYNCTARGET: ${{ secrets.DOWNLOADS_AUTOBUILT_RSYNCTARGET }}
      DOWNLOADS_AUTOBUILT_HOSTKEY: ${{ secrets.DOWNLOADS_AUTOBUILT_HOSTKEY }}
      PULP_FILE_REPO_NAME: ${{ secrets.PULP_FILE_REPO_NAME }}
      PULP_URL: ${{ secrets.PULP_URL }}
      PULP_CONTENT_URL: ${{ secrets.PULP_CONTENT_URL }}
      PULP_CI_USERNAME: ${{ secrets.PULP_CI_USERNAME }}
      PULP_CI_PASSWORD: ${{ secrets.PULP_CI_PASSWORD }}
      PULP_PDNS_GPG_PUBKEY_MASTER: ${{ secrets.PULP_PDNS_GPG_PUBKEY_MASTER }}
      PULP_PDNS_GPG_PUBKEY: ${{ secrets.PULP_PDNS_GPG_PUBKEY }}

  call-build-packages-dnsdist:
    # if: ${{ vars.SCHEDULED_PACKAGES_DAILY }}
    uses: romeroalx/pdns/.github/workflows/build-packages.yml@test-pulp-file-repository
    with:
      product: 'dnsdist'
      is_release: 'YES'
      ref: 'dnsdist-2.0.0-alpha0'
    secrets:
      DOWNLOADS_AUTOBUILT_SECRET: ${{ secrets.DOWNLOADS_AUTOBUILT_SECRET }}
      DOWNLOADS_AUTOBUILT_RSYNCTARGET: ${{ secrets.DOWNLOADS_AUTOBUILT_RSYNCTARGET }}
      DOWNLOADS_AUTOBUILT_HOSTKEY: ${{ secrets.DOWNLOADS_AUTOBUILT_HOSTKEY }}
      PULP_FILE_REPO_NAME: ${{ secrets.PULP_FILE_REPO_NAME }}
      PULP_URL: ${{ secrets.PULP_URL }}
      PULP_CONTENT_URL: ${{ secrets.PULP_CONTENT_URL }}
      PULP_CI_USERNAME: ${{ secrets.PULP_CI_USERNAME }}
      PULP_CI_PASSWORD: ${{ secrets.PULP_CI_PASSWORD }}
      PULP_PDNS_GPG_PUBKEY_MASTER: ${{ secrets.PULP_PDNS_GPG_PUBKEY_MASTER }}
      PULP_PDNS_GPG_PUBKEY: ${{ secrets.PULP_PDNS_GPG_PUBKEY }}

  call-build-packages-rec:
    # if: ${{ vars.SCHEDULED_PACKAGES_DAILY }}
    uses: romeroalx/pdns/.github/workflows/build-packages.yml@test-pulp-file-repository
    with:
      is_release: 'YES'
      product: 'recursor'
      ref: 'rec-5.2.0-rc1'
    secrets:
      DOWNLOADS_AUTOBUILT_SECRET: ${{ secrets.DOWNLOADS_AUTOBUILT_SECRET }}
      DOWNLOADS_AUTOBUILT_RSYNCTARGET: ${{ secrets.DOWNLOADS_AUTOBUILT_RSYNCTARGET }}
      DOWNLOADS_AUTOBUILT_HOSTKEY: ${{ secrets.DOWNLOADS_AUTOBUILT_HOSTKEY }}
      PULP_FILE_REPO_NAME: ${{ secrets.PULP_FILE_REPO_NAME }}
      PULP_URL: ${{ secrets.PULP_URL }}
      PULP_CONTENT_URL: ${{ secrets.PULP_CONTENT_URL }}
      PULP_CI_USERNAME: ${{ secrets.PULP_CI_USERNAME }}
      PULP_CI_PASSWORD: ${{ secrets.PULP_CI_PASSWORD }}
      PULP_PDNS_GPG_PUBKEY_MASTER: ${{ secrets.PULP_PDNS_GPG_PUBKEY_MASTER }}
      PULP_PDNS_GPG_PUBKEY: ${{ secrets.PULP_PDNS_GPG_PUBKEY }}
