---
name: 'daily: build packages for master '

on:
  # push:
  schedule:
    - cron: '0 5 * * *'

permissions:
  actions: read
  id-token: write
  contents: write

jobs:
  call-build-packages-auth:
    # if: ${{ vars.SCHEDULED_PACKAGES_DAILY }}
    uses: romeroalx/pdns/.github/workflows/build-packages.yml@test-pulp-file-repository
    with:
      is_release: 'NO'
      product: 'authoritative'
      ref: test-pulp-file-repository
    secrets:
      PULP_REPO_NAME: ${{ secrets.PULP_REPO_NAME }}
      PULP_URL: ${{ secrets.PULP_URL }}
      PULP_CI_USERNAME: ${{ secrets.PULP_CI_USERNAME }}
      PULP_CI_PASSWORD: ${{ secrets.PULP_CI_PASSWORD }}

  call-build-packages-dnsdist:
    # if: ${{ vars.SCHEDULED_PACKAGES_DAILY }}
    uses: romeroalx/pdns/.github/workflows/build-packages.yml@test-pulp-file-repository
    with:
      is_release: 'NO'
      product: 'dnsdist'
      ref: test-pulp-file-repository
    secrets:
      PULP_REPO_NAME: ${{ secrets.PULP_REPO_NAME }}
      PULP_URL: ${{ secrets.PULP_URL }}
      PULP_CI_USERNAME: ${{ secrets.PULP_CI_USERNAME }}
      PULP_CI_PASSWORD: ${{ secrets.PULP_CI_PASSWORD }}

  call-build-packages-rec:
    # if: ${{ vars.SCHEDULED_PACKAGES_DAILY }}
    uses: romeroalx/pdns/.github/workflows/build-packages.yml@test-pulp-file-repository
    with:
      is_release: 'NO'
      product: 'recursor'
      ref: test-pulp-file-repository
    secrets:
      PULP_REPO_NAME: ${{ secrets.PULP_REPO_NAME }}
      PULP_URL: ${{ secrets.PULP_URL }}
      PULP_CI_USERNAME: ${{ secrets.PULP_CI_USERNAME }}
      PULP_CI_PASSWORD: ${{ secrets.PULP_CI_PASSWORD }}
