---
name: Trigger workflow builder for different releases

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

permissions: # least privileges, see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
  actions: read
  contents: read

jobs:
  call-builder-test-ubuntu-oracular:
    uses: romeroalx/pdns/.github/workflows/builder.yml@test-ubuntu-oracular
    with:
      branch-name: test-ubuntu-oracular
