---
name: Trigger workflow build-and-test-all for different releases

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 22 * * 4'

permissions: # least privileges, see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
  actions: read
  contents: read

jobs:
  call-build-and-test-all-master-debian-11:
    # if: ${{ vars.SCHEDULED_JOBS_BUILD_AND_TEST_ALL }}
    uses: romeroalx/pdns/.github/workflows/build-and-test-all.yml@test-enable-meson-auth-deb11-2
    with:
      branch-name: test-enable-meson-auth-deb11-2
      runner-docker-image-name: base-pdns-ci-image/debian-11-pdns-base
