---
name: Trigger workflow builder for different releases

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

permissions: # least privileges, see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
  actions: read
  contents: read

jobs:
  call-builder-auth-test-fakeroot:
    name: Call builder test-fakeroot
    if: ${{ vars.SCHEDULED_JOBS_BUILDER }}
    uses: romeroalx/pdns/.github/workflows/builder.yml@test-fakeroot
    with:
      branch-name: test-fakeroot
