---
name: Trigger specific coverity scan

on:
  workflow_dispatch:
    inputs:
      product:
        description: Product to build
        type: choice
        options:
        - authoritative
        - recursor
        - dnsdist

permissions: # least privileges, see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
  contents: read

jobs:
  coverity-auth:
    name: coverity scan of the auth
    if: ${{ github.event.inputs.product == 'authoritative' }}
    uses: romeroalx/pdns/.github/workflows/coverity.yml@test-fix-coverity-secrets
    with:
      product: ${{ github.event.inputs.product }}
    secrets:
      COVERITY_TOKEN: ${{ secrets.coverity_auth_token }}
      COVERITY_EMAIL: ${{ secrets.coverity_email }}

  coverity-dnsdist:
    name: coverity scan of dnsdist
    if: ${{ github.event.inputs.product == 'dnsdist' }}
    uses: romeroalx/pdns/.github/workflows/coverity.yml@test-fix-coverity-secrets
    with:
      product: ${{ github.event.inputs.product }}
    secrets:
      COVERITY_TOKEN: ${{ secrets.coverity_dnsdist_token }}
      COVERITY_EMAIL: ${{ secrets.coverity_email }}

  coverity-rec:
    name: coverity scan of the rec
    if: ${{ github.event.inputs.product == 'recursor' }}
    uses: romeroalx/pdns/.github/workflows/coverity.yml@test-fix-coverity-secrets
    with:
      product: ${{ github.event.inputs.product }}
    secrets:
      COVERITY_TOKEN: ${{ secrets.coverity_rec_token }}
      COVERITY_EMAIL: ${{ secrets.coverity_email }}
