---
name: Test triggering specific package build

on:
  push:

permissions: # least privileges, see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
  actions: read
  contents: write # To be able to upload assets as release artifacts
  id-token: write # To sign the provenance in the build packages reusable workflow.

jobs:
  call-build-packages:
    uses: romeroalx/pdns/.github/workflows/custom-build-packages.yml@test-issue-provenance
    with:
      product: authoritative
      os: 'el-8 el-7 el-6'
      ref: master
      is_release: 'NO'
    # secrets:
    #   DOWNLOADS_AUTOBUILT_SECRET: ${{ secrets.DOWNLOADS_AUTOBUILT_SECRET }}
    #   DOWNLOADS_AUTOBUILT_RSYNCTARGET: ${{ secrets.DOWNLOADS_AUTOBUILT_RSYNCTARGET }}
    #   DOWNLOADS_AUTOBUILT_HOSTKEY: ${{ secrets.DOWNLOADS_AUTOBUILT_HOSTKEY }}
