name: "Various daily checks"

on:
  push:
  schedule:
    - cron: '34 4 * * *'

permissions: # least privileges, see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
  contents: read

env:
  CLANG_VERSION: '12'

jobs:
  el7-devtoolset:
    # if: ${{ vars.SCHEDULED_MISC_DAILIES }}
    runs-on: ubuntu-22.04

    steps:
    - name: Check whether a newer devtoolset exists
      run: |
        if docker run --rm centos:7 bash -c 'yum install -y centos-release-scl-rh && yum info devtoolset-12-gcc-c++'
        then
          echo "::warning file=builder-support/dockerfiles/Dockerfile.rpmbuild::A newer devtoolset exists. Please edit builder-support/dockerfiles/Dockerfile.rpmbuild, builder-support/dockerfiles/Dockerfile.rpmbuild, and .github/workflows/dailies.yml"
          exit 1
        else
          echo "::notice ::No newer devtoolset exists (good)"
          exit 0
        fi

  check-debian-autoremovals:
    # if: ${{ vars.SCHEDULED_MISC_DAILIES }}
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 5
        submodules: recursive

    - name: Check if Debian is about to toss us off a balcony
      run: ./build-scripts/check-debian-autoremovals.py

  coverity-auth:
    name: coverity scan of the auth
    # if: ${{ vars.SCHEDULED_MISC_DAILIES }}
    runs-on: ubuntu-22.04
    env:
      # COVERITY_TOKEN: ${{ secrets.coverity_auth_token }}
      FUZZING_TARGETS: no
      SANITIZERS:
      UNIT_TESTS: no
    steps:
      - uses: PowerDNS/pdns/set-ubuntu-mirror@meta
      - uses: actions/checkout@v4
        with:
          fetch-depth: 5
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: build-scripts/gh-actions-setup-inv-no-dist-upgrade
      - run: inv install-clang
      - run: inv install-auth-build-deps
      - run: inv ci-autoconf
      - run: inv ci-auth-configure
      - run: inv ci-auth-make

  coverity-dnsdist:
    name: coverity scan of dnsdist
    # if: ${{ vars.SCHEDULED_MISC_DAILIES }}
    runs-on: ubuntu-22.04
    env:
      # COVERITY_TOKEN: ${{ secrets.coverity_dnsdist_token }}
      SANITIZERS:
      UNIT_TESTS: no
      REPO_HOME: ${{ github.workspace }}
    steps:
      - uses: PowerDNS/pdns/set-ubuntu-mirror@meta
      - uses: actions/checkout@v4
        with:
          fetch-depth: 5
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: build-scripts/gh-actions-setup-inv-no-dist-upgrade
      - run: inv install-clang
      - run: inv install-dnsdist-build-deps --skipXDP
      - run: inv ci-autoconf
        working-directory: ./pdns/dnsdistdist/
      - run: inv ci-build-and-install-quiche ${{ env.REPO_HOME }}
        working-directory: ./pdns/dnsdistdist/
      - run: inv ci-dnsdist-configure full
        working-directory: ./pdns/dnsdistdist/
      - run: inv ci-dnsdist-make
        working-directory: ./pdns/dnsdistdist/

  coverity-rec:
    name: coverity scan of the rec
    # if: ${{ vars.SCHEDULED_MISC_DAILIES }}
    runs-on: ubuntu-22.04
    env:
      # COVERITY_TOKEN: ${{ secrets.coverity_rec_token }}
      SANITIZERS:
      UNIT_TESTS: no
    steps:
      - uses: PowerDNS/pdns/set-ubuntu-mirror@meta
      - uses: actions/checkout@v4
        with:
          fetch-depth: 5
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: build-scripts/gh-actions-setup-inv-no-dist-upgrade
      - run: inv install-clang
      - run: inv install-rec-build-deps
      - run: inv ci-autoconf
        working-directory: ./pdns/recursordist/
      - run: inv ci-rec-configure full
        working-directory: ./pdns/recursordist/
      - run: inv ci-rec-make
        working-directory: ./pdns/recursordist/
