name: "Various daily checks"

on:
  schedule:
    - cron: '34 4 * * *'

permissions: # least privileges, see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
  contents: read

env:
  CLANG_VERSION: '12'

jobs:
  el7-devtoolset:
    runs-on: ubuntu-22.04

    steps:
    - name: Check whether a newer devtoolset exists
      run: |
        if docker run --rm centos:7 bash -c 'yum install -y centos-release-scl-rh && yum info devtoolset-12-gcc-c++'
        then
          echo "::warning file=builder-support/dockerfiles/Dockerfile.rpmbuild::A newer devtoolset exists. Please edit builder-support/dockerfiles/Dockerfile.rpmbuild, builder-support/dockerfiles/Dockerfile.rpmbuild, and .github/workflows/dailies.yml"
          exit 1
        else
          echo "::notice ::No newer devtoolset exists (good)"
          exit 0
        fi

  check-debian-autoremovals:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 5
        submodules: recursive

    - name: Check if Debian is about to toss us off a balcony
      run: ./build-scripts/check-debian-autoremovals.py

  coverity-auth:
    name: coverity scan of the auth
    runs-on: ubuntu-22.04
    env:
      FUZZING_TARGETS: no
      SANITIZERS:
      UNIT_TESTS: no
    steps:
      - uses: PowerDNS/pdns/set-ubuntu-mirror@meta
      - uses: actions/checkout@v4
        with:
          fetch-depth: 5
          submodules: recursive
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.11'
      - run: build-scripts/gh-actions-setup-inv-no-dist-upgrade
      - run: inv install-clang
      - run: inv install-auth-build-deps
      - run: inv ci-autoconf
      - run: inv ci-auth-configure
      - run: inv ci-auth-make
