---
  name: 'Test docker setup'
  
  on:
    push:
  
  permissions: # least privileges, see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
    contents: read
  
  jobs:
    docker:
      name: docker
      runs-on: macos-14
      steps:
        - run: wget https://desktop.docker.com/mac/main/arm64/Docker.dmg
        - run: ps -ef | grep -i Docker; echo
        - run: sudo hdiutil attach Docker.dmg
        - run: sudo /Volumes/Docker/Docker.app/Contents/MacOS/install --accept-license
        - run: sudo hdiutil detach /Volumes/Docker
        - run: open /Applications/Docker.app
        - run: ps -ef | grep -i Docker; echo
        - run: sleep 120
        - run: ps -ef | grep -i Docker; echo
        - run: sudo ln -s /Users/runner/.docker/run/docker.sock /var/run/docker.sock
        - run: /Applications/Docker.app/Contents/Resources/bin/docker ps
        - run: /Applications/Docker.app/Contents/Resources/bin/docker pull alpine:latest
        - run: /Applications/Docker.app/Contents/Resources/bin/docker image ls
