---
  name: 'Test docker setup'
  
  on:
    push:
  
  permissions: # least privileges, see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
    contents: read
  
  jobs:
    docker:
      name: docker
      runs-on: macos-14
      steps:
        - run: brew update && brew upgrade
        - run: brew uninstall qemu
        - run: brew install --build-from-source qemu
        - run: brew pin qemu
        - run: brew install colima docker
        # - run: curl -OSL https://raw.githubusercontent.com/Homebrew/homebrew-core/dc0669eca9479e9eeb495397ba3a7480aaa45c2e/Formula/qemu.rb
        # - run: brew unlink qemu
        # - run: ls; brew install ./qemu.rb
        # - run: uname -m
        # - run: |
        #     cat >entitlements.xml <<EOF
        #     <?xml version="1.0" encoding="UTF-8"?>
        #     <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        #     <plist version="1.0">
        #     <dict>
        #         <key>com.apple.security.hypervisor</key>
        #         <true/>
        #     </dict>
        #     </plist>
        #     EOF
        #     
        #     codesign --sign - --entitlements entitlements.xml --force /usr/local/bin/qemu-system-$(uname -m | sed -e s/arm64/aarch64/)

        - run: colima start --very-verbose
        - run: docker ps
        - run: docker pull alpine:latest
        - run: docker image ls
